### ISSUE TITLE
license headers should mention the LGPL probably

### ISSUE THREAD

**Issue by SoniEx2** [VulpixelMC/world-in-a-jar#16]
currently the headers only reference the GPL but they should probably also mention the LGPL.

(yes this is a mess, welcome to LGPL. but anyway.)

**Comment by sylv256** [comment]
> Insert the word “Lesser” before “General” in all three places in the boilerplate notice to make sure that you refer to the GNU LGPLv3 and not the GNU GPLv3. 

completely missed this, oops
