### ISSUE TITLE
what the mod insall

### ISSUE THREAD

**Issue by DontaeGamez** [VulpixelMC/world-in-a-jar#5]
![image](https://user-images.githubusercontent.com/117000691/208327798-21a8fa85-91b3-4737-b534-e564720813e7.png) what is this

**Comment by Oliver-makes-code** [comment]
You need the Quilt Kotlin Libraries, which you can download here https://modrinth.com/mod/qkl

**Comment by sylv256** [comment]
invalid + question + stale
